// Generated by Wrangler on Tue Jul 16 2024 22:14:46 GMT+0900 (日本標準時)
// by running `wrangler types`

interface Env {
  ENV: string;
  FIREBASE_API_KEY: string;
  FIREBASE_APP_ID: string;
  FIREBASE_AUTH_DOMAIN: string;
  FIREBASE_MESSAGING_SENDER_ID: string;
  FIREBASE_PROJECT_ID: string;
  FIREBASE_STORAGE_BUCKET: string;
  SESSION_SECRET: string;
  CLOUDFLARE_ACCOUNT_ID: string;
  CLOUDFLARE_IMAGES_API_TOKEN: string;
  CLOUDFLARE_IMAGES_PROVIDE_URL: string;
}
