#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-07-01"
name = "frontend"
pages_build_output_dir = "./build/client"

[vars]
CLOUDFLARE_IMAGES_PROVIDE_URL = "https://imagedelivery.net/OYEg37ELuKSl07ux6tX6eA"
ENV = "development"
FIREBASE_API_KEY = "AIzaSyBsZsDljy-CAtK3auolbPINPZEIRhrpU2I"
FIREBASE_APP_ID = "1:1027324171337:web:451ca283d07da6ce3f5b98"
FIREBASE_AUTH_DOMAIN = "serverless-todo-app-e65a1.firebaseapp.com"
FIREBASE_MESSAGING_SENDER_ID = "1027324171337"
FIREBASE_PROJECT_ID = "serverless-todo-app-e65a1"
FIREBASE_STORAGE_BUCKET = "serverless-todo-app-e65a1.appspot.com"

[env.production.vars]
CLOUDFLARE_IMAGES_PROVIDE_URL = "https://imagedelivery.net/OYEg37ELuKSl07ux6tX6eA"
ENV = "production"
FIREBASE_API_KEY = "AIzaSyBsZsDljy-CAtK3auolbPINPZEIRhrpU2I"
FIREBASE_APP_ID = "1:1027324171337:web:451ca283d07da6ce3f5b98"
FIREBASE_AUTH_DOMAIN = "serverless-todo-app-e65a1.firebaseapp.com"
FIREBASE_MESSAGING_SENDER_ID = "1027324171337"
FIREBASE_PROJECT_ID = "serverless-todo-app-e65a1"
FIREBASE_STORAGE_BUCKET = "serverless-todo-app-e65a1.appspot.com"
